# Generated by Django 2.0.3 on 2018-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500000)),
                ('title', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=10, null=True)),
                ('receipient', models.CharField(max_length=250, null=True)),
                ('sender', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Papers',
            },
        ),
    ]
