# Generated by Django 2.0.3 on 2018-09-05 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papel_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papers',
            options={'verbose_name_plural': 'Papers'},
        ),
        migrations.AddField(
            model_name='papers',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
