# Generated by Django 2.0.3 on 2018-09-11 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papel_backend', '0002_auto_20180905_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='receipient',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='sender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
